### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by agvbergin** [Wardley-Mapping-Foundation/wmf-standards-dsl#1]
I think we need a license adding to this repo.

**Comment by tasel** [comment]
What would be the best fit for this? CC-BY-SA?

**Comment by agvbergin** [comment]
Yes, text-based content needs to be CC-BY-SA, following Simon's licensing of mapping.

If there's going to be code in the repo then that needs a software license. Thoughts @spurkis @juliusgb?

**Comment by tasel** [comment]
This will be a text-only-repo as we are going to describe a DSL, not implementing it.
